LiverFup/urls.py
from django.urls import path
from .views import LiverList , LiverPDetailView,AddNewLiverPView
from . import views



urlpatterns = [
    path('LiverList/',LiverList.as_view(), name ='LiverList'),
    path('inrollmentView/<int:pk>',LiverPDetailView.as_view(),name='inrollment-detail'),

    path('add_liverp/',AddNewLiverPView.as_view(),name='add_liverp'),


    ]

NCCVH/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('nntc.urls')),
    path('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
    path('LiverFup/',include('LiverFup.urls')),
    path('admin/', admin.site.urls),
]

nntc/urls.py
from django.urls import path
from . import views
from .views import HomeView,PatientDetailView,AddNewPatientView,UpdatePatientView,DeletePatientView,AddNewW0tView,AddNewW4tView,AddNewW8tView,AddNewW12tView,AddNewW16tView,AddNewW20tView,AddNewW24tView,AddNewW28tView,AddNewW36tView,UpdateW0,UpdateW4,UpdateW8,UpdateW12,UpdateW16,UpdateW20,UpdateW24,UpdateW28,UpdateW36,SearchResultsView, get_data,PhyView,DeletePhyView,UpdatephyView,AddNewPhyView
urlpatterns = [
   # path('',views.home,name="home")

   path('',HomeView.as_view(),name="home"),
   path('search/', SearchResultsView.as_view(), name='search_results'),
   path('patientView/<int:pk>',PatientDetailView.as_view(),name='patient-detail'),
   path('add_patient/',AddNewPatientView.as_view(),name='add_patient'),
   path('patientView/edit/<int:pk>',UpdatePatientView.as_view(),name='update_patient'),
   path('DeleteView/<int:pk>/remove',DeletePatientView.as_view(),name='delete_patient'),
   path('patientView/<int:pk>/followupw0/',AddNewW0tView.as_view(),name='add_w0'),
   path('patientView/<int:pk>/followupw4/',AddNewW4tView.as_view(),name='add_w4'),
   path('patientView/<int:pk>/followupw8/',AddNewW8tView.as_view(),name='add_w8'),
   path('patientView/<int:pk>/followupw12/',AddNewW12tView.as_view(),name='add_w12'),
   path('patientView/<int:pk>/followupw16/',AddNewW16tView.as_view(),name='add_w16'),
   path('patientView/<int:pk>/followupw20/',AddNewW20tView.as_view(),name='add_w20'),
   path('patientView/<int:pk>/followupw24/',AddNewW24tView.as_view(),name='add_w24'),
   path('patientView/<int:pk>/followupw28/',AddNewW28tView.as_view(),name='add_w28'),
   path('patientView/<int:pk>/followupw36/',AddNewW36tView.as_view(),name='add_w36'),
   path('patientView/W0View/edit/<int:pk>',UpdateW0.as_view(),name='update_W0'),
   path('patientView/W4View/edit/<int:pk>',UpdateW4.as_view(),name='update_W4'),
   path('patientView/W8View/edit/<int:pk>',UpdateW8.as_view(),name='update_W8'),
   path('patientView/W12View/edit/<int:pk>',UpdateW12.as_view(),name='update_W12'),
   path('patientView/W16View/edit/<int:pk>',UpdateW16.as_view(),name='update_W16'),
   path('patientView/W20View/edit/<int:pk>',UpdateW20.as_view(),name='update_W20'),
   path('patientView/W24View/edit/<int:pk>',UpdateW24.as_view(),name='update_W24'),
   path('patientView/W28View/edit/<int:pk>',UpdateW28.as_view(),name='update_W28'),
   path('patientView/W36View/edit/<int:pk>',UpdateW36.as_view(),name='update_W36'),
   path('index',views.index,name ='index'),
   path('api/data/',get_data,name = 'api-data'),
   #path('api/chart/data/',ChartsData.as_view()),
   path('phylist/',PhyView.as_view(),name='phyView'),
   path('add_physician/',AddNewPhyView.as_view(),name='add_physician'),


 #  path('data', views.pivot_data, name='pivot_data'),
 #  path('Center/<str:cents>/',CenterView,name = 'center'),
]

LiverFup/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime,date
from ckeditor.fields import RichTextField

# Create your models here.
class inrollment(models.Model):
    patient_name =models.CharField(max_length=200,null=False)
    National_ID =models.CharField( max_length=14,null=False,unique=True)
    Center_ID=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    age = models.IntegerField(null=False)
    Gender_choices=(
        ('Male','Male'),
        ('Female','Female'),
    )
    gender=models.CharField(choices=Gender_choices, max_length=300,null=True,blank=True)



    Comorbidities_choise =(
        ('No Comorbidities','No Comorbidities'),
        ('Cardiac','Cardiac'),
        ('Chest','Chest'),
        ('Renal','Renal'),
        ('Other','Other'),

    )
    Comorbidities = models.CharField(choices=Comorbidities_choise,max_length=50,null=True,blank=True)

    Cause_of_Liver_Cirrhosis_choise= (
        ('HCV','HCV'),
        ('HBV','HBV'),
        ('Other Cuses','Other Cuses'),



    )
    Cause_of_Liver_Cirrhosis=models.CharField(choices=Cause_of_Liver_Cirrhosis_choise,max_length=20,null=True,blank=True)

    in_case_HCV_choise = (
        ('SOF/DAC','SOF/DAC'),
        ('SOF/DAC/RBV','SOF/DAC/RBV'),
        ('PAR/OMB','PAR/OMB'),
        ('PAR/OMB/RBV','PAR/OMB/RBV'),
        ('SOF/DAC/SIM','SOF/DAC/SIM'),
        ('SOF/PAR/OMB/RBV','SOF/PAR/OMB/RBV'),
        ('SOF/LED','SOF/LED'),
        ('IFN/RBV','IFN/RBV'),
        ('SOF/INF/RBV','SOF/INF/RBV'),
        ('SOF/RBV','SOF/RBV'),
        ('SOF/SIM','SOF/SIM'),
        ('SOF/DAC/SIM/RBV','SOF/DAC/SIM/RBV'),
        ('N/A','N/A'),




     )



    HCV_Treatmen_If_not_Pick_Na = models.CharField(
       choices=in_case_HCV_choise
       ,max_length=50,null=True,blank=True)


    in_case_HCV_Out_come_choise = (
        ('Responder','Responder'),
        ('Relapser','Relapser'),
        ('N/A','N/A'),
    )

    In_case_OF_HCV_OutCome = models.CharField(choices=in_case_HCV_Out_come_choise,max_length=50,null=True,blank=True)
    created_on = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.patient_name
    def get_absolute_url(self):
            return reverse ('LiverList')








class Visit(models.Model):
    class Meta:
        unique_together = (('inrollment_id','visit_num'),)

    inrollment_id = models.ForeignKey(inrollment,on_delete=models.CASCADE,related_name='visits')
    visit_num = models.IntegerField(null=False)
    AFP = models.DecimalField(null=True,decimal_places=1,max_digits=4)
    YES_NO_choise = (
         ('Yes', 'Yes'),
         ('NO', 'NO'),
    )
    Presence_of_Ascites =models.CharField(choices=YES_NO_choise,max_length=20,null=True,blank=True)
    Presence_of_Focal_Lesions = models.CharField(choices=YES_NO_choise,max_length=20,null=True,blank=True)
    Performance_Status_In_Presence_of_Focal_Lesions =models.CharField(max_length=200,null=True,blank=True)
    Fib4 = models.DecimalField(null=True,decimal_places=1,max_digits=4,blank=True)
    Child_Score_choise = (
        ('A5','A5'),
        ('A6','A6'),
        ('B7','B7'),
        ('B8','B8'),
        ('B9','B9'),
        ('C','C'),

    )
    Child_Score =models.CharField(choices=Child_Score_choise,max_length=12,null=True,blank=True)
    HCC_Confirmed_by_Triphasic_CT_MRI= models.CharField(choices=YES_NO_choise,max_length=20,null=True,blank=True)
    Method_of_HCC_Confirmation_choise = (
        ('Triphasic CT','Triphasic CT'),
        ('MRI','MRI'),
    )
    Method_of_HCC_Confirmation = models.CharField(max_length=20,choices=Method_of_HCC_Confirmation_choise,null=True,blank=True)
    Number_of_focal_lesions = models.IntegerField(null=True,blank=True)
    Site_Segment = models.IntegerField(null=True,blank=True)
    Size_In_case_of_Multiple_lesions_mention_the_largest = models.CharField(max_length=50,null=True,blank=True)
    Attach_CT_Report_and_CT_Images_If_possible = models.FileField(upload_to='report',null=True,blank=True)
    Period_between_HCV_Cure_HCC_in_Months = models.IntegerField(null=True,blank=True)
    Hemoglobin = models.IntegerField(null=True,blank=True)
    Platelet_count = models.IntegerField(null=True,blank=True)
    WBCx103mm3 = models.IntegerField(null=True,blank=True)
    INR = models.DecimalField(null=True,decimal_places=1,max_digits=3,blank=True)
    Total_BILIRUBIN_mgdL = models.IntegerField(null=True,blank=True)
    Albumin_gdL= models.DecimalField(null=True,decimal_places=2,max_digits=4,blank=True)
    AST_IUL =models.DecimalField(null=True,decimal_places=2,max_digits=4)
    ALT_IUL =models.DecimalField(null=True,decimal_places=2,max_digits=4)
    Creatinine=models.DecimalField(null=True,decimal_places=2,max_digits=4,blank=True)
    date_of_the_last_dose = models.DateField(null=True,blank=True)
    Fup_befor = models.CharField(choices=YES_NO_choise,null=True ,max_length=20,blank=True)
    create_on = models.DateField(auto_now_add=True)



    def __str__(self):
        return  str(self.inrollment_id)

LiverFup/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker


from .models import inrollment,Visit


class inrollmentForm(forms.ModelForm):

    National_ID =forms.CharField(max_length=14,validators=[RegexValidator('(2|3)[0-9][1-9][0-1][1-9][0-3][1-9](01|02|03|04|11|12|13|14|15|16|17|18|19|21|22|23|24|25|26|27|28|29|31|32|33|34|35|88)\d\d\d\d\d',message="please enter avalid national ID")],widget=forms.NumberInput( attrs={ 'class':"form-control"}))


    age = forms.IntegerField(max_value=100,min_value=18 ,widget=forms.NumberInput( attrs={ 'class':"form-control"}))

    class Meta:

       model = inrollment
       fields = ('patient_name','National_ID','age','Center_ID','gender','Comorbidities','Cause_of_Liver_Cirrhosis',
       'HCV_Treatmen_If_not_Pick_Na','In_case_OF_HCV_OutCome')

       widgets = {
               'patient_name':forms.TextInput(attrs={ 'class':"form-control"}),
              'gender':forms.Select(attrs={ 'class':"form-control"}),
              'Center_ID':forms.TextInput(attrs={ 'class':"form-control",'value':'','id':'emji','type':'hidden'}),
              'Comorbidities' :forms.Select(attrs={ 'class':"form-control"}),
              'Cause_of_Liver_Cirrhosis':forms.Select(attrs={ 'class':"form-control"}),
              'HCV_Treatmen_If_not_Pick_Na':forms.Select(attrs={ 'class':"form-control"}),
              'In_case_OF_HCV_OutCome':forms.Select(attrs={ 'class':"form-control"}),

          }

LiverFup/views.py
from django.shortcuts import render , get_object_or_404
from django.views.generic import ListView,DetailView,CreateView,UpdateView, DeleteView
from  .models import inrollment ,Visit
from .forms import inrollmentForm
from django.urls import reverse_lazy , reverse
from django.http import HttpResponseRedirect

# Create your views here.

class LiverList(ListView):
    model= inrollment
    template_name = 'LiverFup/LiverHome.html'
    ordering =['-created_on']
    paginate_by = 20

class LiverPDetailView(DetailView):
    model =inrollment
    template_name ='LiverFup/inrollment_detail.html'

class AddNewLiverPView(CreateView):
    model=inrollment
    form_class =inrollmentForm
    template_name ='LiverFup/add_lpatient.html'


        ###########################################follow up start add here
#class AddNewVisittView(CreateView):
 #   model=Visit
  #  form_class =VisitForm
   # template_name ='LiverFup/add_Visit.html'
   # fields='__all__'
#    def form_valid(self,form):
 #       form.instance.patient_id = self.kwargs['pk']
  #      return super().form_valid(form)
   # success_url = reverse_lazy('LiverList')

LiverFup/templates/LiverFup/LiverHome.html
 {% extends 'base.html' %} {% block title%}home page {% endblock%} {% block content%} {% if user.is_authenticated %}
<h1>Patient List </h1>

<strong class="number"><span>All Patient :</span>{{ pcount }}</strong>
<table class ="table">
<thead>
      <tr>
        <th>Patient Name</th>
        <th>National ID</th>
        <th>Patient Center</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Createon</th>
        <th > &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Actions </th>
      </tr>
    </thead>

    <tbody>
 {% for inrollment in inrollment_list %} {% if user.id == inrollment.Center_ID.id %}
      <tr>
    
      <td> {{inrollment.patient_name}}</td>
        <td><a href="{% url 'inrollment-detail' inrollment.pk %}">{{inrollment.National_ID}}</td>
        <td>{{inrollment.Center_ID}}</td>
        <td>{{inrollment.created_on}}</td>
         <td> <a type="button" class="btn btn-info btn-sm" href="#">Update</a>
         
          
        <a type="button" class="btn btn-danger btn-sm" href="#">Delete</a> </td>
      
      </tr>
      {% endif %}{% endfor %}
    </tbody>
  </table>

 {% else %}
<strong>please login</strong> {% endif %} {% endblock%}

LiverFup/templates/LiverFup/add_lpatient.html
{% extends 'base.html' %} {% block title%}add Patient {% endblock%}{% block content%} {% if user.is_authenticated %}


<h1>Add New Patient For Liver Fup </h1>
<div class="form-group">
    <form method="POST">
        {% csrf_token %} {{form.media}}{{form.as_p}}






        <button class="btn btn-secondary">Save</button>

</div>
<script>
    var name = "{{user.id}}";
    document.getElementById("emji").value = name;
</script>

{% else %}
<strong>Please Login</strong> {% endif %} {% endblock%}

LiverFup/templates/LiverFup/inrollment_detail.html
{% extends 'base.html' %} {% block title%}Patient detail{% endblock%} {% block content%}

<head>
    <style>
        table,
        td,
        th {
            border: 1px solid #ddd;
            text-align: left;
        }
        
        table {
            border-collapse: collapse;
            width: 100%;
        }
        
        th,
        td {
            padding: 15px;
        }
    </style>
</head>
{% if user.is_authenticated %} {% if user.id == inrollment.Center_ID.id %}

<h1>Patient detail View</h1>
<a class="btn btn-info" href="#">Edit</a> -
<a class="btn btn-info" href="#">Delete</a></h1>
<br/>
<hr>
<P style="background-color:#efeff5;font-size: 20px;text-align:center; color: rgb(111, 179, 235);"><b>Patient information</b></P>
<table class="table table-bordered">

    <tbody>
        <tr>
            <th><strong>Patient  Name </strong>: </th>
            <td> <strong>Center ID : </strong> </td>
            <td><strong>National ID : </strong></td>
            <td><strong>Gender : </strong></td>
            <td><strong>Age : </strong></td>
            <td><strong>Comorbidities : </strong> </td>
        </tr>

    </tbody>
    <tbody>
        <tr>
            <th>{{inrollment.patient_name}}</th>
            <td>{{inrollment.Center_ID}}</td>
            <td>{{inrollment.National_ID}}</td>
            <td>{{inrollment.gender}}</td>
            <td>{{inrollment.age}}</td>
            <td>{{inrollment.Comorbidities}}</td>
        </tr>

    </tbody>
</table>
<table>
    <tbody>
        <tr>
            <th><strong>Cause of Liver Cirrhosis</strong></th>
            <td><strong>HCV Treatmen If not Pick Na</strong></td>
                <td><strong>In case OF HCV OutCome</strong></td>
                <td><strong>created on</strong></td>
                
        </tr>

    </tbody>


    <tbody>
        <tr>
            <th>{{inrollment.Cause_of_Liver_Cirrhosis}}</th>
            <td>
                {{inrollment.HCV_Treatmen_If_not_Pick_Na}}</td>
            <td>{{inrollment.In_case_OF_HCV_OutCome}}</td>
            <td>{{inrollment.created_on}}</td>
            
        </tr>

    </tbody>
</table>

<!-------- Start Week 0 View ------>
<h2>Follow up </h2>
{% if not inrollment.visits.all %} no visits  for this patient Yet <a href="#">add one </a> {% else %} <p>{% for visit in inrollment.visits.all %} Visit info : <a class="text-info"> Visit number</a>: {{ visit.visit_num }}-<a class="text-info">-Created on </a>: {{visit.create_on}} --<a type ="button" class ="btn btn-primary btn-sm" href="#">Update</a>
<a type="button" class="btn btn-danger btn-sm" href="#">Delete</a></p><hr>{%endfor%} {% endif %}



<br/>
<br/>
<hr>
<hr> {% else %} you are not allow here !! {% endif %} {% else %}

<strong>Please Login</strong> {% endif %} {% endblock %}